#### Build and tests all pushes, also code coverage
name: CI build
on: [push, pull_request]
jobs:
    build:
        name: Build sources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-dotnet@v1
            - name: Build code
              run: dotnet build
            - name: Test code
              run: dotnet test -v minimal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./codecover/lcov.info

            - name: Publish coverage report to coveralls.io
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                path-to-lcov: ./codecover/lcov.info
