#### Publish tags to docker hub
name: Deploy to Docker Hub for master
on:
   push:
     branches:
      - master

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --compress \
            --tag netdaemon/netdaemon:dev
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v6 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --compress \
            --tag netdaemon/netdaemon:dev-v6
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --compress \
            --tag netdaemon/netdaemon:dev-v7