#### Publish tags to docker hub
name: Deploy to Docker Hub for master
on:
   push:
     branches:
      - master

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

      # Build
      - name: Build image
        if: success()
        run: |
          docker build \
            --compress \
            --no-cache \
            -t netdaemon/netdaemon:latest \
            -f Dockerfile .

      # Deploy
      - name: Push image to docker registry [latest]
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push netdaemon/netdaemon:latest