#### Publish tags to docker hub
name: Deploy dev builds to Docker Hub
on:
   push:
     branches:
      - master

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Set version number"
        run: |
          sed -i '/        const string _version = /c\        const string _version = "master build";' ${{github.workspace}}/src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm,linux/arm64,linux/amd64 \
            --output "type=image,push=true" \
            --no-cache \
            --file ./Dockerfile . \
            --compress \
            --tag netdaemon/netdaemon:latest
