#### Build and tests all pushes, also code coverage
name: publish nuget
on:
  push:
    tags:
      - '*'

jobs:
  deploy_nuget:
    name: publish nuget packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v1
      - uses: olegtarasov/get-tag@v2
        name: Set tag envronment variable
      - name: "Set version number"
        run: |
          sed -i '/        private const string Version = /c\        private const string Version =  "${GIT_TAG_NAME}";' ${{github.workspace}}/src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
      - name: pack DaemonRunner
        run: dotnet pack src/DaemonRunner/DaemonRunner/DaemonRunner.csproj --configuration Release -p:PackageVersion=${GIT_TAG_NAME}-beta
      - name: pack App
        run: dotnet pack src/App/NetDaemon.App/NetDaemon.App.csproj --configuration Release -p:PackageVersion=${GIT_TAG_NAME}-beta
      - name: pack Daemon
        run: dotnet pack src/Daemon/NetDaemon.Daemon/NetDaemon.Daemon.csproj --configuration Release -p:PackageVersion=${GIT_TAG_NAME}-beta
      - name: pack Test
        run: dotnet pack tests/NetDaemon.Test/NetDaemon.Test.csproj --configuration Release -p:PackageVersion=${GIT_TAG_NAME}-beta
      - name: push to nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --no-symbols true
