#### Publish tags to docker hub
name: Deploy to Docker Hub for tags
on:
   push:
     tags:
       - '*'

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      # - uses: olegtarasov/get-tag@v2
      #   name: Set tag envronment variable
      - name: "Set version number"
        run: |
          sed -i '/        private const string Version = /c\        private const string Version =  "${GITHUB_REF#refs/tags/}";' ${{github.workspace}}/src/DaemonRunner/DaemonRunner/Service/RunnerService.cs
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm, linux/amd64 \
            --output "type=image,push=true" \
            --no-cache \
            --file ./Dockerfile . \
            --compress \
            --tag netdaemon/netdaemon:latest \
            --tag netdaemon/netdaemon:${GITHUB_REF#refs/tags/}